### ISSUE TITLE
Partially-rendered WMS request via MapCache with metatiling

### ISSUE THREAD

**Issue by maddenp** [mapserver/mapcache#134]
I have been having a problem with WMS requests at certain zoom levels returning only partial maps when metatiling is enabled. To demonstrate, consider these requests, made directly on my MapServer / MapCache system:
```
% wget "http://localhost:8080/mapserv/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=GLIMS_GLACIERS&CRS=EPSG%3A3857&STYLES=&WIDTH=2880&HEIGHT=907&BBOX=-18339451.266430914%2C5959407.98948631%2C-4250578.212907228%2C10396424.60738422" -O mapserver_direct.png

% wget "http://localhost/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=GLIMS_GLACIERS&CRS=EPSG%3A3857&STYLES=&WIDTH=2880&HEIGHT=907&BBOX=-18339451.266430914%2C5959407.98948631%2C-4250578.212907228%2C10396424.60738422" -O mapcache_metatiling_on.png

% wget "http://localhost/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=GLIMS_GLACIERS&CRS=EPSG%3A3857&STYLES=&WIDTH=2880&HEIGHT=907&BBOX=-18339451.266430914%2C5959407.98948631%2C-4250578.212907228%2C10396424.60738422" -O mapcache_metatiling_off.png
```
I am running MapServer on port 8080, and only on localhost, so the first request goes directly to MapServer.

For the second request, I deleted the sqlite3 cache file and restarted Apache. My mapcache.xml contains, in its single &lt;tileset&gt; block:
```
<metatile>2 2</metatile>
<metabuffer>10</metabuffer>
```
For the third request, I removed the &lt;metatile&gt; and &lt;metabuffer&gt; entries, deleted the sqlite3 cache file and restarted Apache.

The resultant image files are attached. The image returned by MapCache without metatiling is essentially identical to the one returned directly by MapServer (the image shows glaciers in Alaska on the left, in and in Greenland on the right). In the image returned by MapCache with metatiling, the glaciers in western North America are missing. The problem appears in just two zoom levels; at all other levels, the Alaskan glaciers appear. And, by only changing the &lt;metatile&gt; tag, I can push the problem to different zoom levels -- but cannot seem to get rid of it.

Maybe this is a configuration problem and not a bug. I would be grateful for any ideas, and happy to answer any questions.

This is MapServer 7.0 and MapCache commit f10eb9bd5a35009a0fe23b52a27ae8cf19ec1932, both built from source on Ubuntu 14.04.
![mapcache_metatiling_off](https://cloud.githubusercontent.com/assets/1868662/10900702/3b00b452-81a0-11e5-9f7a-677dbd619bf1.png)
![mapcache_metatiling_on](https://cloud.githubusercontent.com/assets/1868662/10900704/3b031e2c-81a0-11e5-9e76-ef86aff5c160.png)
![mapserver_direct](https://cloud.githubusercontent.com/assets/1868662/10900703/3b0256f4-81a0-11e5-8317-b1957c5ebf91.png)

**Comment by tbonfort** [comment]
Can you trace the requests made by mapcache to mapserver, after emptying the sqlite cache. They should appear in your apache access logs with the mod-mapcache user-agent string. Then replay those requests directly in a browser and report back.

**Comment by p-madden** [comment]
After deleting my sqlite cache file and zeroing the Apache logs, I mimic the WMS request made by my web app:
```
# wget "http://localhost?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=GLIMS_GLACIERS&CRS=EPSG%3A3857&STYLES=&WIDTH=3840&HEIGHT=1568&BBOX=-28808266.66036866%2C2992428.299568898%2C8762061.482361175%2C18333645.62451691" -O /dev/null
```
Here are the requests made by MapCache to MapServer:
```
# cat /var/log/apache2/mapcache-access.log
::1 - - [03/Nov/2015:10:58:57 -0700] "GET /mapserv?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&STYLES=&BBOX=-20135347.738994%2c-97839.396205%2c97839.396205%2c20135347.738994&WIDTH=2068&HEIGHT=2068&FORMAT=image%2fpng&SRS=EPSG%3a3857&LAYERS=GLIMS_GLACIERS&TRANSPARENT=true HTTP/1.1" 200 16948 "-" "mod-mapcache/1.4.0"
::1 - - [03/Nov/2015:10:58:57 -0700] "GET /mapserv?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&STYLES=&BBOX=-97839.396205%2c-97839.396205%2c20135347.738994%2c20135347.738994&WIDTH=2068&HEIGHT=2068&FORMAT=image%2fpng&SRS=EPSG%3a3857&LAYERS=GLIMS_GLACIERS&TRANSPARENT=true HTTP/1.1" 200 182646 "-" "mod-mapcache/1.4.0"
```
Now I make those requests directly to MapServer:
```
# wget "http://localhost:8080/mapserv?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&STYLES=&BBOX=-20135347.738994%2c-97839.396205%2c97839.396205%2c20135347.738994&WIDTH=2068&HEIGHT=2068&FORMAT=image%2fpng&SRS=EPSG%3a3857&LAYERS=GLIMS_GLACIERS&TRANSPARENT=true" -O r1.png
# wget "http://localhost:8080/mapserv?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&STYLES=&BBOX=-97839.396205%2c-97839.396205%2c20135347.738994%2c20135347.738994&WIDTH=2068&HEIGHT=2068&FORMAT=image%2fpng&SRS=EPSG%3a3857&LAYERS=GLIMS_GLACIERS&TRANSPARENT=true" -O r2.png
```
The resultant images are attached: The first is blank, and the second looks as it should. If I turn metatiling off in my mapcache.xml and do all of this again, MapCache makes 6 requests (instead of 2) to MapServer, and the resultant images all appear to contain reasonable data.
![r1](https://cloud.githubusercontent.com/assets/13628927/10917848/0bc8f264-8220-11e5-8a89-ee49e6a99590.png)
![r2](https://cloud.githubusercontent.com/assets/13628927/10917847/0bc83126-8220-11e5-81e8-97b06c3ce5f9.png)

**Comment by p-madden** [comment]
I notice that the minx=-20135347.738994 value for the "bad" URL is outside the extent of my grid, which is a verbatim copy of the "GoogleMapsCompatible" grid documented [here](http://mapserver.org/sq/mapcache/config.html), only with &lt;size&gt;1024 1024&lt;/size&gt;. If I change BBOX in the “bad” URL so that minx=-20037508.3427892480, to match the grid extent, MapServer returns a correct-looking map.

For what it’s worth, I also notice that the maxy value, and both the maxx and maxy values of the “good” URL, are also outside the extent, which does not seem to matter.

I'm new to MapCache and MapServer and do not know whether MapServer should be able to handle values outside the defined extent, or whether MapCache should not be requesting them.
Or something else entirely.

**Comment by tbonfort** [comment]
the 1024 tiles are your issue, as they overshoot the dateline for zoom levels 0 and 1 which is probably confusing the wms server. Stick to 256 tiles, or adjust your grid resolutions so that no single tile can be larger than than +/- 20037508

**Comment by maddenp** [comment]
With 1024x1024 tiles, the problem appears at zoom levels 3 and 4. I changed to 256x256 tiles (and also tried reverting to using the pre-defined "GoogleMapsCompatible" grid), and the problem shifted to levels 1, 2 and 3. With the smaller tiles the problem does indeed seem to be limited to areas near the date line (both in the north and, as I see now, in the south, too).

**Comment by maddenp** [comment]
I found the cause of my troubles. The provisioner for my virtual machine was installing, from Ubuntu's packages, an old MapServer, and it was the mapserv CGI executable from this package that was being called by MapCache. When I eliminated this package, and ensured that the v7.0.0 mapserver I'd built from source was being used, the blank-tiles problem disappeared. I'm now using 1024x1024 tiles with 2x2 metatiling without problems. Sorry about the bogus bug report...
